-d C:\git\TangCartMSX\RTL\tangnano20k_vdp_cartridge_rev2_step1\impl\gwsynthesis\tangnano20k_vdp_cartridge_tncart_rev1.vg
-p GW2AR-18C-QFN88-8
-pn GW2AR-LV18QN88C8/I7
-cst C:\git\TangCartMSX\RTL\tangnano20k_vdp_cartridge_rev2_step1\src\tangnano20k_vdp_cartridge_tncart_rev1.cst
-cfg C:\git\TangCartMSX\RTL\tangnano20k_vdp_cartridge_rev2_step1\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-place_option 2
-route_option 2
-correct_hold 1
-route_maxfan 23
